### ISSUE TITLE
`buildHtml` doesn't work inside generic procs

### ISSUE THREAD

**Issue by dawkot** [pragmagic/karax#101]
Code:
```nim
proc foo[A](x: A) =
  discard buildHtml(tdiv):
    text ":)"

foo ":)"
```
Error:
> Expected a node of kind nnkIdent, got nnkSym

**Comment by timotheecour** [comment]
I ran into this when trying to pass `action = proc() | EventHandler` which would simplify code

**Comment by geotre** [comment]
Also getting problems with this
