### ISSUE TITLE
useless if-else branch

### ISSUE THREAD

**Issue by TommyLemon** [pragmagic/karax#113]
line 64-67
```nim
      if this.status == 200:
        contWrapper(this.status, this.responseText)
      else:
        contWrapper(this.status, this.responseText)
```
https://github.com/pragmagic/karax/blob/master/karax/kajax.nim

**Comment by gogolxdong** [comment]
It's my code, fixed. You can use my forking, enhanced inline style ,input value, sessionstorage and websocket. https://github.com/gogolxdong/karax . I also noticed you are in Shenzhen, we have a QQ group 469329878, welcome to discuss Karax further.
