### ISSUE TITLE
regression: Failed to execute 'replaceChild' on 'Node' when using `dthunk`

### ISSUE THREAD

**Issue by timotheecour** [pragmagic/karax#121]
```
karun -r main.nim
open page in browser
click on button
```
in console log, shows: 
```
Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at apply_patch_526222 (file:///Users/timothee/git_clone/nim/timn/nimcache/main.js:2486:24)
    at dodraw_529246 (file:///Users/timothee/git_clone/nim/timn/nimcache/main.js:2618:3)
    at HEX3Aanonymous_530601 (file:///Users/timothee/git_clone/nim/timn/nimcache/main.js:2671:5)
```
and the output html is wrong:
```
Temp
0 txt:2
1 txt:3
2 # should not be here
3 # should not be here
4 txt:4
```

reduced example:
```nim
import karax / [kbase, vdom, kdom, karax, karaxdsl]
import std/jsffi

var velements: seq[Node]
for i in 0..<5: # s/5/4 would work
  let v = document.createTextNode("txt:" & $i)
  # v.id = "id:" & $i # doesn't help
  velements.add v

proc createDom*(): VNode =
  result = buildHtml(tdiv):
    button():
      text "Temp"
      proc onclick() =
        velements = velements[2..^1]
    for i, v in velements:
      tdiv:
        text $i & " "
        dthunk(v)

when isMainModule:
  setRenderer createDom, "ROOT"
```

## note
marking as regression because before e422087 (exponential dom diffing) it wasn't throwing `replaceChild` error; however it's only a half-regression as the output was not correct, showing:
```
0 txt:0
1 txt:1
2 txt:2
```
instead of:
```
0 txt:2
1 txt:3
2 txt:4
```

## note
weirdly, `0..<4` would not result in bug, unlike `0..<5`

/cc @araq this bug is a blocker; unlike https://github.com/pragmagic/karax/issues/56 (where I could add a unique id), I don't know of a workaround

**Comment by Araq** [comment]
Workaround:

```nim

import karax / [kbase, vdom, kdom, karax, karaxdsl]
import std/jsffi

var velements: seq[Node]
for i in 0..<5: # s/5/4 would work
  let v = document.createTextNode("txt:" & $i)
  # v.id = "id:" & $i # doesn't help
  velements.add v

proc createDom*(): VNode =
  result = buildHtml(tdiv):
    button():
      text "Temp"
      proc onclick() =
        velements = velements[2..^1]
        avoidDomDiffing()
    for i, v in velements:
      tdiv:
        text $i & " "
        dthunk(v)

when isMainModule:
  setRenderer createDom, "ROOT"
```

**Comment by timotheecour** [comment]
unfortunately it's a bit drastic of a workaround; avoidDomDiffing does fix this particular reduced example but causes other issues in my original use case, eg:
* re-rendering the whole DOM is expensive in my use case (lots of images + other elements)
* avoidDomDiffing causes a change of behavior when DOM has some state that isn't fully captured by the vdom, which can happen when mixing components with third party libs, etc

**Comment by Araq** [comment]
Bummer. :-(

**Comment by timotheecour** [comment]
here's another workaround: code below works; it adds a `id = nextId()` which generates a new unique id; this is really not great either but at least, unlike avoidDomDiffing, can be localized to particular nodes in the DOM (not global effect on entire DOM)

hopefully the root cause can be addressed without this workaround...

```nim
when defined case2b:
  #[
  workaround
  ]#
  import karax / [kbase, vdom, kdom, karax, karaxdsl]
  import std/jsffi

  var velements: seq[Node]
  for i in 0..<5: # 0..<4 would not result in bug
    let v = document.createTextNode("txt:" & $i)
    # v.id = "id:" & $i # doesn't help
    velements.add v

  var id0 = 0
  proc nextId(): kstring =
    result = kstring("zid_" & $id0)
    id0.inc

  proc createDom*(): VNode =
    result = buildHtml(tdiv):
      button():
        text "Temp v15"
        proc onclick() =
          velements = velements[2..^1]
      for i, v in velements:
        tdiv(id=nextId()): # workaround
          text $i & " "
          dthunk(v)

  when isMainModule:
    setRenderer createDom, "ROOT"
```

## note
looks like karax is missing `keys` from https://reactjs.org/docs/reconciliation.html#keys ; note that `id` is not a viable replacement because it affects other operations (eg getElementById, etc) and keys doesn't have to be globally unique, only unique within its siblings; note also that VCompenent has key, but not VNode


## EDIT:
see https://github.com/pragmagic/karax/pull/122 which seems to fix this issue
