### ISSUE TITLE
buildHtml produces nimsuggest error

### ISSUE THREAD

**Issue by moigagoo** [pragmagic/karax#131]
I'm not sure if this is a Karax issue or a nimsuggest issue, so apologies if I'm reporting it to the wrong repo.

The problem is that nimsuggest reports an error even with the simplest Karax code simply if `buildHtml` is called:
```
import karax/[karax, karaxdsl, vdom]

proc render(): VNode =
  buildHtml(tdiv):
    p:
      text "hello"

setRenderer render
```

Nimsuggest output (via nimlsp in Sublime Text; in VScode, I'm getting "illformed AST"):
```
 ◌ public\root.nim:
        5:12  	nimsuggest chk	error     	template/generic instantiation from here
       75:7   	nimsuggest chk	error     	cannot generate VM code for result
```

**Comment by Araq** [comment]
Does nimsuggest know the target is JS? You have to set ``--define: js`` in your configuration.

**Comment by moigagoo** [comment]
Thanks for the hint! I've added this `config.nims` to the same folder where the file is sitting:
```
switch("define", "js")
```

I can see nimlsp catch that config on server start:
```
nim: Hint: used config file 'C:\Users\moigagoo\Projects\chyatik\public\config.nims' [Conf]
```

However, the error persists.

Tried using `root.nim.cfg` instead of `config.nims`, the result is the same.

**Comment by moigagoo** [comment]
Just to keep the report pure from possible editor or LSP-related issues, here's the output I'm getting with vanilla nimsuggest:
```
$ nimsuggest.exe root.nim
Hint: used config file 'C:\Users\moigagoo\.choosenim\toolchains\nim-1.0.4\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\moigagoo\Projects\chyatik\public\root.nim.cfg' [Conf]
usage: sug|con|def|use|dus|chk|mod|highlight|outline|known file.nim[;dirtyfile.nim]:line:col
type 'quit' to quit
type 'debug' to toggle debug mode on/off
type 'terse' to toggle terse mode on/off
> chk root.nim
chk     skUnknown               Hint    ???     0       -1      "root [Processing]"     0
chk     skUnknown               Error   C:\Users\moigagoo\Projects\chyatik\public\root.nim      5       11      "template/generic instantiation from here"      0
chk     skUnknown               Error   C:\Users\moigagoo\.nimble\pkgs\karax-1.1.0\karax\karaxdsl.nim   75      6      "cannot generate VM code for result"     0
```

**Comment by Araq** [comment]
It's a nimsuggest bug, you may want to move the issue to there. But yeah, it's bad and I hope we can fix it soon.

**Comment by moigagoo** [comment]
Moved to nimsuggest https://github.com/nim-lang/nimsuggest/issues/112
