### ISSUE TITLE
Void elements (input, img, br, etc.) html output not self-closing

### ISSUE THREAD

**Issue by nhanb** [pragmagic/karax#133]
Example:

```nim
import karax / [vdom, karaxdsl]
echo build_html input(class="foo")
echo build_html br()

# Expected:
<input class="foo" />
<br />

# Got:
<input class="foo"></input>
<br></br>
```
In practice, browsers are lenient enough to ignore the closing tag except for `br` where it's actually treated as 2 `<br>` tags (at least on Firefox). This can be sidestepped by just using `verbatim("<br/>")`, but imo karax should output correct HTML in the first place.

I think this can be fixed by defining a list of all void elements then adding another conditional [in vdom.nim right above here](https://github.com/pragmagic/karax/blob/f6bda9ae892ec93e728e56c260f6628d4f404a28/karax/vdom.nim#L437-L441), something like `elif n.kind in VOID_ELEMENTS: result.add(" />")`.

I can make a pull request if all this sounds reasonable.

**Comment by Araq** [comment]
Please go ahead and exuse my slow reply. What you said makes perfect sense to me.

**Comment by nhanb** [comment]
Cool! I've made my PR here https://github.com/pragmagic/karax/pull/134
