### ISSUE TITLE
[AssertionError] Karax throws exception when used together with xterm.js

### ISSUE THREAD

**Issue by TheSimpleZ** [pragmagic/karax#137]
### The problem 
Output from javascript console
```
expected 0 real 1 DIV nesting 1
Error: Error: unhandled exception: /home/zrean/.nimble/pkgs/karax-1.1.0/karax/karax.nim(597, 14) `same(kxi.currentTree, document.getElementById(kxi.rootId))`  [AssertionError]
Traceback (most recent call last)
redraw.:anonymous, line: 637
karax.dodraw, line: 597
assertions.failedAssertImpl, line: 27
assertions.raiseAssert, line: 20
sysFatal.sysFatal, line: 39
```
I think the output is from here:
https://github.com/pragmagic/karax/blob/2936245d399eecfca81b0cf714e5113cba0724bc/karax/karax.nim#L204-L205

### Background

I'm trying to interface with [xterm.js](https://xtermjs.org/). The exceptions is thrown if I create an input field and make the onkeyupenter event write the text to xterm.

### Reproduction and the code

index.nim:
```nim
import karax / [kbase, vdom, kdom, karax, karaxdsl]
import jsffi

const term_id = kstring"terminal"

var terminal: JsObject
proc newTerminal*(): JsObject {.importjs: "new Terminal()", nodecl.}
proc open*(term: JsObject, parent: JsObject): void {.importjs: "#.open(@)".}
proc write*(term: JsObject, data: string, callback: proc(): void): void {.
    importjs: "#.write(@)".}

proc xterm(): VNode =
  result = buildHtml(tdiv(id = term_id))

proc inputField(): VNode =
  result = buildHtml:
    input:
      proc onkeyupenter(ev: Event, target: VNode) = terminal.write(target.text)

proc postRender() =
  let thediv = getElementById(term_id)
  terminal = newTerminal()
  terminal.open(thediv)

proc createDom(): VNode =
  result = buildHtml(tdiv):
    xterm()
    inputField()

setRenderer createDom, "ROOT", postRender
```
Compile with `karun index.nim`

Add these lines to the `<head>` tag of the html that karun outputs:
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/xterm@4/css/xterm.min.css">
<script src="https://cdn.jsdelivr.net/npm/xterm@4/lib/xterm.min.js"></script>
```

Open the index.html in chrome browser.
Input text into the input field and press Enter.
Check the dev console.

Any ideas of what could be causing this?

#### Nim version
Nim Compiler Version 1.0.6 [Linux: amd64]

**Comment by Araq** [comment]
You need to tell Karax to ignore this DOM node via ``karax.setForeignNodeId``.

**Comment by TheSimpleZ** [comment]
Nope, now xterm creates a new terminal inside the div with id "terminal" when i write to it :confused:
