### ISSUE TITLE
Conditionally redraw with event handler

### ISSUE THREAD

**Issue by geotre** [pragmagic/karax#152]
Is it possible to prevent redraws after an event handler has fired?

In my use case I have attached a handler to the `drag` event, which triggers a lot of redraws when I don't need it to. I noticed that `KaraxInstance` has a `surpressRedraws` boolean but I'm not sure if manually setting/unsetting this is the right approach.

**Comment by Araq** [comment]
You're supposed to use ``surpressRedraws`` indeed.
