### ISSUE TITLE
Deprecate tree procs

### ISSUE THREAD

**Issue by planetis-m** [pragmagic/karax#183]
afaik they re only used in one place that can be replaced by newVNode and outside the library none [seems](https://github.com/search?l=Nim&q=tree%20karax&type=Code) to use them.

**Comment by Araq** [comment]
Does ``tree`` harm though? Karax is past version 1.0, I don't like code breakages just because nobody uses my software. Chicken and egg, nobody can use it if it keeps breaking. ;-)

**Comment by planetis-m** [comment]
Apologies, it's a bit rushed to take such action, I just didn't thought it could work with my svg patch.
