### ISSUE TITLE
Documentation or Tutorials?

### ISSUE THREAD

**Issue by define-private-public** [pragmagic/karax#19]
This really is a neat little project.  After looking at some of the examples, the TODO one seems to be the best one, but I'm having a little difficulty of trying to make sense of how this framework... well... works.  I understand that this is still in early development and in an experimental phase, but something would be nice.

**Comment by bluenote10** [comment]
Not sure if it is of much help already, because it is still very early, but I have started to push the results of my experiments into a small example repo: https://github.com/bluenote10/KaraxExamples

**Comment by define-private-public** [comment]
They are, thanks.

I'm wondering about how other things work like routes and whatnot.  They're kind of the cornerstone of single page apps, but if there is no documentation on how to use them, it makes it a little difficult in Karax.  I did do some poking, and the `setOnHashChange()` proc seem to be what's used, but there's no docstring for it in the source.

**Comment by Araq** [comment]
Well better docs will come with time. Today we reached an important milestone: A component system that might actually work nicely for complex stateful components. :-)

**Comment by define-private-public** [comment]
That's good.  Do routes still work using the `#` symbol?

**Comment by Araq** [comment]
Yes why wouldn't it.

**Comment by define-private-public** [comment]
Sorry for the week late reply.  I was wondering about it because I've seen many other SPA libraries and applications that done use `#`.  Instead, they change the browser's URL and tinker with the history state:

https://developer.mozilla.org/en-US/docs/Web/API/History_API

**Comment by Araq** [comment]
Now there is also: https://nim-lang.org/araq/karax.html
