### ISSUE TITLE
is there a way to pass argument to dom event callback?

### ISSUE THREAD

**Issue by sclee15** [pragmagic/karax#48]
hello

i want to pass fixed arguments to dom event callback.

i hope it would like this

for option in self.product.options:

button(onclick=onDelClick("A3333", ev, node)):

"A3333" is fixed.

do you have any suggestion?

**Comment by Araq** [comment]
Use a closure?

**Comment by sclee15** [comment]
@Araq Thank you for reply. is it possible to insert a nonamed proc in buildhtml?

**Comment by timotheecour** [comment]
@sclee15 you can do any of the following IIRC:

```nim
# option 1:
button(onclick=() => onDelClickAux1("A3333"))

# option 2:
button():
  proc onclick() = discard

# option 3:
proc onDelClickAux2(a: string): auto =
  result = proc (ev: Event; target: VNode) =
    discard
button(onclick=onDelClickAux2("A3333"))
```

I think this issue could be closed.
