### ISSUE TITLE
The nimble package specifies a version of nim compiler 0.16.1

### ISSUE THREAD

**Issue by AjBreidenbach** [pragmagic/karax#6]
I thought 0.16.0 was the latest version...
Am I missing something? :)

Tried it anyway, lowered the version requirement, but obviously nothing's compiling

**Comment by AjBreidenbach** [comment]
I guess disregard this 0.16.1 is now the latest version

**Comment by AjBreidenbach** [comment]
I guess disregard this 0.16.1 is now the latest version

**Comment by AjBreidenbach** [comment]
Is anyone else not able to build something with this, I'm getting the following error
```
/home/andrew/Developer/projects/nim/karax/karax/src/components.nim(82, 13) Error: type mismatch: got (NimNode, proc (bl: typed, op: string): NimNode{.noSideEffect.}, void)
but expected one of: 
proc add(x: var cstring; y: cstring)
proc add[T](x: var seq[T]; y: openArray[T])
proc add(x: var string; y: cstring)
proc add[T](x: var seq[T]; y: T)
proc add(x: var string; y: string)
proc add(x: var string; y: char)
proc add(parent, kid: VNode)
proc add(c: ClassList; class: cstring)
proc add[A, B](t: var OrderedTable[A, B]; key: A; val: B)
proc add(father, child: NimNode): NimNode
proc add[A, B](t: TableRef[A, B]; key: A; val: B)
proc add(father: NimNode; children: varargs[NimNode]): NimNode
proc add[A, B](t: var Table[A, B]; key: A; val: B)
proc add[A, B](t: OrderedTableRef[A, B]; key: A; val: B)
```

**Comment by bluenote10** [comment]
Version 0.16.1 just means that you have to run Nim from the devel branch, which is always one version step ahead of the latest released version. If you want to run the newest stuff like this it is in general best to run Nim from the git repo. Started using karax yesterday and it compiles fine for me using the devel branch.

**Comment by ivanflorentin** [comment]
I have the same problem trying to compile with  0.17.0

**Comment by Araq** [comment]
What command does fail?
