### ISSUE TITLE
scrollapp.nim(20, 12) Error: undeclared field: 'key'

### ISSUE THREAD

**Issue by timotheecour** [pragmagic/karax#74]
nim js scrollapp.nim
scrollapp.nim(20, 12) Error: undeclared field: 'key'

**Comment by o5k4r** [comment]
Many examples don't work, not only this. That makes it really difficult to get started with karax :(

**Comment by Araq** [comment]
Works here, I used the command:

```

tools\karun -r examples\scrollapp\scrollapp.nim

```

**Comment by timotheecour** [comment]
indeed!
