### ISSUE TITLE
karax examples should use import instead of include

### ISSUE THREAD

**Issue by timotheecour** [pragmagic/karax#76]
https://github.com/pragmagic/karax/blob/master/experiments/echartstest.nim uses import:
`import karax / [kbase, vdom, kdom, vstyles, karax, karaxdsl, jdict, jstrutils, jjson]`

but https://github.com/pragmagic/karax/blob/master/readme.rst uses include:
`include karax / prelude`

import is cleaner IMO; include should only be used when import doesn't work.

**Comment by Araq** [comment]
But ``include karax / prelude`` is what's useful for small example programs, the explicit imports are for longer programs, I like both.

**Comment by timotheecour** [comment]
what about having a module `common` that re-exports all of these, then simply:
`import karax / common`

**Comment by Araq** [comment]
I don't like the ``export`` feature and think my way is cleaner, ``include`` for quick-n-dirty, ``import`` for explicit code. :-)
