### ISSUE TITLE
Support for elements not managed by Karax, within Karax app

### ISSUE THREAD

**Issue by nepeckman** [pragmagic/karax#83]
I'm running into some issues using Karax in a project. I have embedded the Monaco editor within my Karax app, and redraw operations fail. The `same` proc returns false when it detects the outside changes in the DOM. Is there an existing workaround to this issue? If not, I'm happy to add the functionality myself and submit a PR. All I need is some guidance on the best way to solve this problem. I can also provide more details if needed!

**Comment by Araq** [comment]
Checkout this example program, esp the marked line https://github.com/pragmagic/karax/blob/master/experiments/echartstest.nim#L58

**Comment by nepeckman** [comment]
Thank you, I appreciate the help!
