### ISSUE TITLE
Pre-rendering HTML?

### ISSUE THREAD

**Issue by ratiotile** [pragmagic/karax#90]
Is it possible to render to static html file, perhaps during compile? Similar to [React's renderToString()](https://reactjs.org/docs/react-dom-server.html#rendertostring), it would allow faster browser rendering before the JS has loaded (Isomorphic sites), and fallback if JS is disabled. 

If the HTML files could be generated at compile time, Karax could be used as a static site generator. I have been using [Gatsby](https://www.gatsbyjs.org/) and am looking at replacing JS entirely with Nim.

Looks like karun currently generates a blank html template. How much work would be required to implement pre-render and reconciliation with the virtual DOM?

**Comment by Araq** [comment]
Have a look at this example: https://github.com/pragmagic/karax/blob/master/tests/nativehtmlgen.nim

It's possible.

**Comment by ratiotile** [comment]
Seems that karun needs to compile the site to executable first and run to generate the .html files, before compiling to js?

I don't see how I'd run createDom() otherwise.

**Comment by ratiotile** [comment]
Update: I have static html generation working. Karax just replaces the root div when it loads. I'll need to figure out how to initialize vdom with the static html.

**Comment by Araq** [comment]
You don't need karun for this, compile with ``nim c ...``

**Comment by dom96** [comment]
if you do get this working please consider documenting/including this functionality in Karax. It's something I've wanted for a while.

**Comment by Araq** [comment]
See/use ``nim c tests/nativehtmlgen.nim`` for an example, it exists.

**Comment by xyb** [comment]
I have added a document about this: #162
